---
## /opt/baremetal is the staging directory.
- name: Mounting source directory from official production ESXi ISO . . . copying over build files . . . backing up defaults . . .
  shell: |
    mkdir /mnt/{{ item }}
    mount -o loop -t iso9660 /ansible/files/isos/{{ src_iso_file }} /mnt/{{ item }}/
    mkdir -p /opt/baremetal/{{ item }}
    mkdir -p /opt/baremetal/temp/{{ item }}
    mkdir -p /opt/baremetal/temp/{{ item }}/etc/vmware/weasel
    cp -r /mnt/{{ item }}/* /opt/baremetal/{{ item }}/
    umount /mnt/{{ item }}
  become: true

## The following two tasks will make the custom iso bootable by both legacy and UEFI implementations:    
- name: Copying custom boot.cfg to root directory . . .
  copy:
    src: /ansible/files/{{ esxi_build }}/boot.cfg
    dest: /opt/baremetal/{{ item }}
    owner: root
    group: root
    mode: '0744'
  become: true


- name: Copying custom UEFI boot.cfg to root efi directory . . .
  copy:
    src: /ansible/files/{{ esxi_build }}/efi/boot/boot.cfg
    dest: /opt/baremetal/{{ item }}/efi/boot
    owner: root
    group: root
    mode: '0744'
  become: true


- name: copy  kickstart
  template:
    src: "./templates/{{ item}}.cfg"
    dest: "/opt/baremetal/{{ item }}/KS.CFG"
  become: true

- name: Creating bootable iso from all files . . .
  shell: >
    mkisofs
    -relaxed-filenames
    -J
    -R
    -b isolinux.bin
    -c boot.cat
    -no-emul-boot
    -boot-load-size 4
    -boot-info-table
    -eltorito-alt-boot
    -e efiboot.img
    -boot-load-size 1
    -no-emul-boot
    -o /ansible/files/esxi/{{ item }}.iso
    /opt/baremetal/{{ item }}/
  become: true

- name: remove directories
  shell: |
    rm -rf /opt/baremetal
    rm -rf /mnt/{{item}}
  become: true

...
