# Let NetworkManager manage all devices on this system
network:
  ethernets:
    ens33:
      dhcp4: false
      activation-mode: manual
    ens37:
      addresses:
        - "{{octet}}.1/26"
      routes:
        - to: default
          via: "{{octet}}.1"
  version: 2
  renderer: NetworkManager
