---

#Server Vars#########################################################################################################################################
ntp: "{{ octet}}.1"

CP1:
  Name: CP1
  IP: "{{ octet }}.30"
  Subnet: "255.255.255.1092"
  datastore: "CP1_VMStore"
  smc: "/ansible/files/smc1"
  server:
    Hostname: "CP1"
    IP: "{{ octet }}.11"
    Subnet: "255.255.255.0"
    Gateway: "{{ octet }}.1"
    mgmt_nic: "vmnic0" 
    iso_path: "/ansible/files/esxi/CP1.iso"
    vmotion: "{{ octet }}.242"
    License: "{{license[0]}}"
  

CP2:
  Name: CP2
  IP: "{{ octet }}.31"
  Subnet: "255.255.255.0"
  datastore: "CP2_VMStore"
  smc: "/ansible/files/smc2"
  server:
    Hostname: "CP2"
    IP: "{{ octet }}.12"
    Subnet: "255.255.255.0"
    Gateway: "{{ octet }}.1"
    mgmt_nic: "vmnic0" 
    iso_path: "/ansible/files/esxi/CP2.iso"
    vmotion: "{{ octet }}.243"
    License:  "{{license[1]}}"

CP3:
  Name: CP3
  IP: "{{ octet }}.32"
  Subnet: "255.255.255.0"
  datastore: "CP3_VMStore"
  smc: "/ansible/files/smc3"
  server:
    Hostname: "CP3"
    IP: "{{ octet }}.13"
    Subnet: "255.255.255.0"
    Gateway: "{{ octet }}.1"
    mgmt_nic: "vmnic0" 
    iso_path: "/ansible/files/esxi/CP3.iso"
    vmotion: "{{ octet }}.244"
    License: "{{license[2]}}"


#VM Vars#########################################################################################################################################
VCSA:
  Name: "VCSA-01"
  IP: "{{ octet }}.10"
  Prefix: "26"
  Gateway: "{{ octet }}.1"
  Subnet: "255.255.255.0"
  Interface_1: "{{ vlan2 }}"
  Username: '{{vcsa_user}}@{{ domain }}.local'
  esxi_infrastructure_fqdn: "{{ octet }}.5"
  Hostname: 'VCSA-01'
  domain: '{{domain}}.local'
  searchpath: ""
  size: 'small'
  ova_file: '{{ vcsa_ova }}'
  network: 'VM Network'
  datacenter_name: '{{domain}}'
  vm_folder: '{{domain}}_VMS'
  License: "{{ vcenter_license }}"


#####