---
#Splunk Vars ########################################
indexgenkey: "{{ indexpasskey }}"
genkey: "{{ passkey }}"
encryptedpassword: "{{encryptedPass}}"

#Server Vars#####################################
ntp: "{{ octet}}.1"

{% for x in range(0,Nodes) %}
{% set server = (loop.index - 1) %}
CP{{loop.index}}:
  Name: CP{{loop.index}}
  IP: "{{ octet }}.3{{server}}"
  Subnet: "255.255.255.192"
  datastore: "CP{{loop.index}}_VMStore"
  smc: "/ansible/files/smc{{loop.index}}"
  server:
    Hostname: "CP{{loop.index}}"
    IP: "{{ octet }}.1{{loop.index}}"
    Subnet: "255.255.255.192"
    Gateway: "{{ octet }}.1"
    mgmt_nic: "vmnic0" #Must be VMNIC0 or else PXE will fail due to 8 port switch
    iso_path: "/ansible/files/esxi/CP{{loop.index}}.iso"
    vmotion: "{{ octet }}.242"
    License: {{license[server]}}

{% endfor %}

{% for x in range(0,Sensors) %}
{% set sensor = (loop.index - 1) %}
{% set ip = (loop.index +2) %}
MR{{sensor}}:
  Name: MR{{sensor}}
  IP: "{{ octet }}.3{{ip}}"
  Subnet: "255.255.255.192"
  os_drives:
    - "sda"
  data_drives:
    - "sdb"
    - "sdc"
    - "sdd"
  server:
    Name: "SOSensor{{sensor}}"
    IP: "{{ octet }}.21{{loop.index}}"
    Subnet: "255.255.255.240"
    Gateway: "{{ octet }}.209"
    Prefix: "28"
    mgmt_nic: "eno1"
    monitor_nic:
      - "eno2"
      - "eno3"
      - "eno4"
    Username: "{{so_default_user}}"
    iso_path: "/ansible/files/so/SOsensor{{sensor}}.iso"

{% endfor %}



#VM Vars#####################################
VCSA:
  Name: "VCSA-01"
  IP: "{{ octet }}.10"
  Prefix: "26"
  Gateway: "{{ octet }}.1"
  Subnet: "255.255.255.192"
  Interface_1: "{{ vlan2 }}"
  Username: 'administrator@{{ TeamKitNum }}.mil'
  esxi_infrastructure_fqdn: "{{ octet }}.5"
  Hostname: 'VCSA-01'
  domain: '{{TeamKitNum}}.mil'
  searchpath: ""
  size: 'small'
  ova_file: 'VMware-vCenter-Server-Appliance-7.0.3.01300-21290409_OVF10.ova'
  datastore: 'CP2_VMStore'
  filestore: 'datastore1'
  network: 'VM Network'
  datacenter_name: '{{TeamKitNum}}'
  vm_folder: '{{TeamKitNum}}_VMS'
  License: "{{ vcenter_license }}"
  Deploy_loc: "{{octet}}.12"

 
PA:
  Name: "PaloAlto"
  IP: "{{ octet }}.2"
  Subnet: "255.255.255.192"
  Interface0: "Management"
  Interface1: "Management"
  Interface2: "Domain Services"
  Interface3: "Data Analysis"
  Interface4: "Host Interrogation"
  Interface5: "Host Data Collection"
  Interface6: "Network Data Collection"
  Interface7: "VMotion"
  Interface10: "Provisioning"
  Interface9: "External"
  loc: "{{ octet }}.13"
  Storage: "100"
  Mem: "150000"
  CPU: "2"
  Username: 'admin'
  deploy_type: "ova"
  datastore: "CP3_VMStore"
  netmask: "255.255.255.192"
  Gateway: "{{ octet }}.1"

DC1:
  IP: "{{ octet }}.130"
  Subnet: "255.255.255.192"
  Interface_1: "{{ vlan10 }}"
  loc: "{{ octet }}.11"
  Storage: "80"
  Mem: "8000"
  CPU: "2"
  deploy_type: "ova"
  datastore: 'CP1_VMStore'

DC2:
  IP: "{{ octet }}.131"
  Subnet: "255.255.255.192"
  Gateway: "{{ octet }}.1"
  Interface_1: "{{ vlan10 }}"
  loc: "{{ octet }}.13"
  Storage: "80"
  Mem: "8000"
  CPU: "2"
  deploy_type: "ova"
  datastore: 'CP3_VMStore'

#Splunk VM Vars ########################################

Splunk_Manager:
  Name: "CM1"
  IP: "{{ octet }}.194"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.11"
  Storage: "500"
  Mem: "16000"
  CPU: "12"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"
  datastore: 'CP1_VMStore'

Splunk_Search:
  Name: "SH1"
  IP: "{{ octet }}.198"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.12"
  Storage: "500"
  Mem: "32000"
  CPU: "16"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"
  datastore: 'CP2_VMStore'

Splunk_Forward:
  Name: "Splunk_Forward"
  IP: "{{ octet }}.228"
  IP2: "{{ octet }}.199"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.225"
  Gateway2: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.13"
  Storage: "500"
  Mem: "12000"
  CPU: "12"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"
  datastore: 'CP3_VMStore'

Splunk_Indexer:
  Name: "IDX"
  IP: "{{ octet }}.19"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.11"
  Storage: "10000"
  Mem: "64000"
  CPU: "18"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"

# SecurityOnion VM vars

SOManager:
  Name: "SOManager"
  IP: "{{ octet }}.210"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.209"
  Prefix: "28"
  Interface_1: "{{ vlan50 }}"
  loc: "{{ octet }}.13"
  Storage: "500"
  CPU: "4"
  Mem: "32000"
  esheap: "8192" # 33% of Mem
  lsheap: "4096" # No greater than 25% or 4gb
  soc: {{so_default_user}}@{{TeamKitNum}}.mil
  Username: "{{so_default_user}}"
  deploy_type: "iso"
  iso_path: "SOManager.iso"
  datastore: 'CP2_VMStore'
  isostore: 'CP2_FileStore'

SOSearch:
  Name: "SOSearch"
  IP: "{{ octet }}.217"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.209"
  Prefix: "28"
  Interface_1: "{{ vlan50 }}"
  loc: "{{ octet }}.13"
  Storage: "500"
  CPU: "8"
  Mem: "24000"
  esheap: "7920" #33% of mem
  Username: "{{so_default_user}}"
  deploy_type: "iso"
  iso_path: "SOSearch.iso"
  datastore: 'CP2_VMStore'
  isostore: 'CP2_FileStore'





#####